import type { Metadata } from "next";
import {  Dancing_Script } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const roboto = Dancing_Script({ weight: '400',variable: "--font-Dancing_Script",subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
      <div className="fixed">  </div>
      {children}</body>
    </html>
  );
}
